### PR TITLE
Fix Query::_where phpdoc

### PR DESCRIPTION
**Pull request by mvorisek**

### CODE REVIEW

**Comment by mvorisek** [comment]
@AllanJard do you have notifications for this repo enabled?

**Comment by AllanJard** [comment]
Yes. 

If what you are actually asking is why haven't I fixed the linting errors yet, it's because I have prioritised it over other things. I consider this important, and the other things I've been working on recently more important.

I will do it as soon as I can.

**Comment by mvorisek** [comment]
> If what you are actually asking is why haven't I fixed the linting errors yet, it's because I have prioritised it over other things.

Thank you for the reply. I pinged you mainly as this PR is done, it fixes one single phpdoc issue.

> I consider this important, and the other things I've been working on recently more important.

I develop and maintain PHP projects professionally. I do not know the financial background of this project and how/if it is tested etc., but if a long term maintenance on paid basis of this PHP project would help you, feel free to get in touch. One of my many public references is https://github.com/atk4/data.

**Comment by AllanJard** [comment]
Sorry - yes - Monday morning grogginess! This could be merged, although there is the outstanding question I posted above of if it should be `string|null`, which I think it should be, since `null` is valid as a value there. That was the only reason that it hasn't been merged yet.

**Comment by mvorisek** [comment]
nullable native type/default value implies null in phpdoc even if not omit - https://phpstan.org/r/7932c1fd-1bdb-4cf9-a18d-15b474a37ee6

as nulls in phpdoc are very often omit thanks to this static analysers behaviour, I do not recommend specifying/worrying null in phpdocs if implied

**Comment by AllanJard** [comment]
Thank you!

**Pull request merged**
